name: Demo Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Utiliser le Secret
      run: echo "Le secret est ${{ secrets.DEMO_SECRET }}"
