name: Time workflow

on: 
  schedule:
    - cron: '58 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: 

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Exécution de Job 2"

