name: Tag workflow

on:
  push:
    tags:
      - 'v*'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

    - name: Step 0
      run: echo "Exécution de Job 1"


  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Exécution de Job 2"

