name: Mon Workflow Python

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Exécuter le script Python
      env:
        MON_SECRET: ${{ secrets.MON_SECRET }}
      run: |
        python mon_script.py
